services:
  titiler:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "127.0.0.1:8888:8000"
    environment:
      # GDAL config
      - CPL_TMPDIR=/tmp
      - GDAL_CACHEMAX=75%
      - GDAL_INGESTED_BYTES_AT_OPEN=32768
      - GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR
      - GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=YES
      - GDAL_HTTP_MULTIPLEX=YES
      - GDAL_HTTP_VERSION=2
      - PYTHONWARNINGS=ignore
      - VSI_CACHE=TRUE
      - VSI_CACHE_SIZE=536870912
      # TiTiler config
      # - TITILER_API_DISABLE_STAC=TRUE/FALSE
      # - TITILER_API_DISABLE_MOSAIC=TRUE/FALSE
      # - TITILER_API_DISABLE_COG=TRUE/FALSE
      # - TITILER_API_DISABLE_ZARR=TRUE/FALSE
      # - TITILER_API_CORS_ORIGIN=url.io,url.xyz
      # - TITILER_API_CACHECONTROL=public, max-age=3600
      # - TITILER_API_DEBUG=TRUE/FALSE
      # appsettings
      - APP_ENABLE_DOCS=false
      - APP_ENABLE_TILEJSON=false
      - APP_ALLOWED_TMS=WebMercatorQuad
      - APP_ROUTE_MODE=dev

    volumes:
      - ./frontend:/frontend:ro
