services:
  alleinsein:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile
    image: base_alleinsein
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # GDAL config
      # - CPL_TMPDIR=/tmp
      # - GDAL_CACHEMAX=75%
      # - GDAL_INGESTED_BYTES_AT_OPEN=32768
      # - GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR
      # - GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=YES
      - GDAL_HTTP_MULTIPLEX=YES
      - GDAL_HTTP_VERSION=2
      # - PYTHONWARNINGS=ignore
      # - VSI_CACHE=TRUE
      # - VSI_CACHE_SIZE=536870912
      # TiTiler config
      # - APP_ENABLE_DOCS=False
      # - APP_ALLOWED_TMS=WebMercatorQuad
      # - APP_ENV=dev

    volumes:
      - ./backend:/backend
      - ./raster/out:/raster/out

    # run uvicorn app
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload --proxy-headers --forwarded-allow-ips "*"

    healthcheck:
      test: ["CMD", "bash", "/scripts/smoke-test.sh"]
      interval: 120s
      timeout: 10s
      retries: 2
      start_period: 5s
