AREA="germany"
OVERWRITE="--overwrite"
# OVERWRITE=""

TARGET_EPSG="EPSG:3035"
WEB_EPSG="EPSG:3857"

RASTER_RESOLUTION="20,20"
RASTER_NODATA="255"
RASTER_DATA_TYPE="Byte"

# GDAL/OSM memory and temporary file settings.
# Allow GDAL to use up to 2GB RAM for block caching.
GDAL_CACHEMAX="2048"
# Keep OSM node indexing in memory up to 2GB.
OSM_MAX_TMPFILE_SIZE="2048"
# Redirect temporary files to WSL native /tmp.
CPL_TMPDIR="/tmp"

# Shared raster bounds in TARGET_EPSG.
# Keep these aligned to 100m boundaries to avoid clipping artifacts when
# combining 20m and 100m rasters.
# Get new values with:
# python ./raster/scripts/export_bounds.py
MINX="4031300"
MINY="2684000"
MAXX="4672600"
MAXY="3556600"

GTIFF_WRITE_OPTIONS=(
  "--of=GTiff"
  "--co=TILED=YES"
  "--co=COMPRESS=DEFLATE"
  "--co=PREDICTOR=2"
  "--co=BIGTIFF=IF_SAFER"
)
