AREA="germany"
# OVERWRITE="--overwrite"
OVERWRITE=""

TARGET_EPSG="EPSG:3035"
WEB_EPSG="EPSG:3857"

RASTER_RESOLUTION="20,20"
RASTER_NODATA="255"
RASTER_DATA_TYPE="Byte"

# Shared raster bounds in TARGET_EPSG.
# Keep these aligned to 100m boundaries to avoid clipping artifacts when
# combining 20m and 100m rasters.
# Get new values with:
# python ./raster/scripts/export_bounds.py
MINX="4031300"
MINY="2684000"
MAXX="4672600"
MAXY="3556600"

GTIFF_WRITE_OPTIONS=(
  "--of=GTiff"
  "--co=TILED=YES"
  "--co=COMPRESS=DEFLATE"
  "--co=PREDICTOR=2"
  "--co=BIGTIFF=IF_SAFER"
)
