name: Version bump

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  bump-version:
    if: ${{ !startsWith(github.event.head_commit.message, 'bump:') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Bump version
        id: commitizen
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog: false
          no_raise: 21
          check_consistency: true

      - name: Print version
        run: echo "Bumped to ${{ steps.commitizen.outputs.version }}"
